# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen', '0002_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attendances', to='manajemen.Practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
