# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen', '0003_practiceattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(default='', max_length=50)),
                ('user', models.ManyToManyField(related_name='kelas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='practiceattendance',
            name='user',
        ),
        migrations.AddField(
            model_name='practiceattendance',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_attendances', to='manajemen.Kelas'),
        ),
    ]
