# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen', '0004_auto_20170406_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceattendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='practiceattendance',
            name='is_present',
            field=models.ManyToManyField(related_name='practice_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
