# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0007_article_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=20)),
                ('nominal', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
