# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen', '0008_administrasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstype', models.CharField(max_length=20)),
                ('nominal', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='administrasi',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='administrasi',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='administrasi',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='administrasi',
            name='jenis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrasi_jenis', to='manajemen.AdministrationType'),
        ),
        migrations.AlterField(
            model_name='administrasi',
            name='nominal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrasi_nominal', to='manajemen.AdministrationType'),
        ),
    ]
