# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0010_auto_20170411_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrasi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/bukti_payments'),
        ),
    ]
