# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0012_auto_20170417_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
