# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0014_practiceattendance_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={'ordering': ['-updated_date']},
        ),
    ]
