# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0015_auto_20170418_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceattendance',
            old_name='created_date',
            new_name='updated_date',
        ),
    ]
