# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0016_auto_20170418_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceattendance',
            name='is_present',
            field=models.ManyToManyField(blank=True, related_name='practice_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practiceattendance',
            name='tutor_pendamping',
            field=models.ManyToManyField(blank=True, related_name='tutor_pendamping_practice_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
