# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0017_auto_20170418_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrasi',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
