# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0018_administrasi_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thingsname', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('detail', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='practiceattendance',
            options={'ordering': ['-practice']},
        ),
        migrations.AlterField(
            model_name='practice',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
