# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 03:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0019_auto_20170430_1315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrasi',
            managers=[
                ('saldo', django.db.models.manager.Manager()),
            ],
        ),
    ]
