# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0021_practiceattendance_daftar_orang'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_mainarticle',
            field=models.BooleanField(default=False),
        ),
    ]
