# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0023_auto_20170504_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_concertarticle',
            field=models.BooleanField(default=False),
        ),
    ]
