# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0027_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='updated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
