# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen', '0028_auto_20170513_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kelas_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_kelas_before', to='manajemen.Kelas')),
                ('kelas_current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_kelas_current', to='manajemen.Kelas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_kelas_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_date'],
            },
        ),
    ]
