# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0029_logkelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='user',
        ),
    ]
