# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manajemen', '0030_remove_kelas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date_meet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_meeting_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
