# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0031_auto_20170514_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
