# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0033_auto_20170515_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrasi',
            name='nominal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
