# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0036_article_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrasi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/bukti_payments'),
        ),
        migrations.AlterField(
            model_name='administrasi',
            name='nominal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
