# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0040_article_is_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
    ]
