# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0041_auto_20171002_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='note',
        ),
    ]
