# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen', '0042_remove_inventory_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={},
        ),
    ]
