# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20170323_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('deal', 'Deal'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='waiting', max_length=20),
        ),
    ]
