# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20170323_1359'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='event',
        #     name='event_id',
        # ),
        # migrations.AddField(
        #     model_name='event',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
