# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_userprofile_tipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_registration_paid',
            field=models.BooleanField(default=False),
        ),
    ]
