# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_userprofile_is_registration_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('wanita', 'Wanita'), ('pria', 'Pria')], default='pria', max_length=10),
        ),
    ]
