# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_auto_20170411_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingsvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('email1', models.CharField(max_length=50)),
                ('email2', models.CharField(max_length=50)),
            ],
        ),
    ]
