# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_settingsvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsvalue',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='settingsvalue',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='settingsvalue',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='settingsvalue',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='settingsvalue',
            name='phone2',
        ),
        migrations.AddField(
            model_name='settingsvalue',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settingsvalue',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settingsvalue',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
