# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_auto_20170425_0407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settingsvalue',
            new_name='SettingsVariable',
        ),
    ]
