# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20170425_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/slider')),
                ('caption', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=40)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
