# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_auto_20170503_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pobirth',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
