# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_auto_20170503_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
