# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0021_userprofile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
    ]
