# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_remove_userprofile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pobirth',
            field=models.DateField(blank=True, max_length=40, null=True),
        ),
    ]
