# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0023_auto_20170504_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plbirth',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pobirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
