# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_userprofile_user_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
