# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_auto_20170513_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plbirth',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipe_user',
            field=models.CharField(choices=[('member', 'Member'), ('tutor', 'Tutor')], default='member', max_length=20),
        ),
    ]
