# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0030_auto_20170513_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_have_kelas',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='manajemen.Kelas'),
        ),
    ]
