# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0031_auto_20170513_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
    ]
