# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import public.validators


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0032_auto_20170515_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(upload_to='files/events', validators=[public.validators.validate_file_extension], verbose_name='proposal atau undangan'),
        ),
    ]
