# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0034_auto_20170522_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
