# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0035_auto_20170522_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
