# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0039_auto_20170525_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-updated_date']},
        ),
    ]
