# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0041_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuenstionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField(max_length=255, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
