# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0043_auto_20170925_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuenstionAnswer',
            new_name='QuestionAnswer',
        ),
    ]
